insert into public.exercises
(name, category, muscle_primary, muscle_secondary, equipment_required, difficulty, animation_key, met)
values
('Barbell Back Squat','strength','{"quads","glutes"}'::text[],'{"hamstrings","core","lower_back"}'::text[],'{"barbell","rack"}'::text[],'intermediate','squat',6.0),
('Goblet Squat','strength','{"quads","glutes"}'::text[],'{"core"}'::text[],'{"dumbbells"}'::text[],'beginner','squat',5.0),
('Air Squat','strength','{"quads","glutes"}'::text[],'{"core"}'::text[],'{}'::text[],'beginner','squat',4.0),
('Romanian Deadlift','strength','{"hamstrings","glutes"}'::text[],'{"lower_back","core"}'::text[],'{"barbell"}'::text[],'intermediate','deadlift',5.5),
('Conventional Deadlift','strength','{"hamstrings","glutes","lower_back"}'::text[],'{"quads","traps","core"}'::text[],'{"barbell"}'::text[],'advanced','deadlift',7.0),
('Barbell Hip Thrust','strength','{"glutes"}'::text[],'{"hamstrings","core"}'::text[],'{"barbell","bench"}'::text[],'intermediate','hipThrust',5.0),
('Glute Bridge','strength','{"glutes"}'::text[],'{"hamstrings"}'::text[],'{}'::text[],'beginner','hipThrust',3.5),
('Barbell Bench Press','strength','{"chest"}'::text[],'{"triceps","front_delts"}'::text[],'{"barbell","bench"}'::text[],'intermediate','benchPress',5.5),
('Dumbbell Bench Press','strength','{"chest"}'::text[],'{"triceps","front_delts"}'::text[],'{"dumbbells","bench"}'::text[],'beginner','benchPress',5.0),
('Overhead Barbell Press','strength','{"front_delts","side_delts"}'::text[],'{"triceps","upper_chest","core"}'::text[],'{"barbell"}'::text[],'intermediate','shoulderPress',5.5),
('Dumbbell Shoulder Press','strength','{"front_delts"}'::text[],'{"triceps","side_delts"}'::text[],'{"dumbbells"}'::text[],'beginner','shoulderPress',5.0),
('Pull-up','strength','{"lats","biceps"}'::text[],'{"rhomboids","rear_delts"}'::text[],'{"pullup_bar"}'::text[],'intermediate','pullup',8.0),
('Chin-up','strength','{"biceps","lats"}'::text[],'{"rhomboids"}'::text[],'{"pullup_bar"}'::text[],'intermediate','pullup',7.5),
('Assisted Pull-up','strength','{"lats","biceps"}'::text[],'{"rhomboids"}'::text[],'{"pullup_bar"}'::text[],'beginner','pullup',6.0),
('Barbell Bicep Curl','strength','{"biceps"}'::text[],'{"forearms"}'::text[],'{"barbell"}'::text[],'beginner','bicepCurl',3.5),
('Dumbbell Bicep Curl','strength','{"biceps"}'::text[],'{"forearms"}'::text[],'{"dumbbells"}'::text[],'beginner','bicepCurl',3.5),
('Hammer Curl','strength','{"biceps","brachialis"}'::text[],'{"forearms"}'::text[],'{"dumbbells"}'::text[],'beginner','bicepCurl',3.5),
('Tricep Dip','strength','{"triceps"}'::text[],'{"chest","front_delts"}'::text[],'{"bench"}'::text[],'beginner','tricepDip',4.5),
('Parallel Bar Dip','strength','{"triceps","chest"}'::text[],'{"front_delts"}'::text[],'{"parallel_bars"}'::text[],'intermediate','tricepDip',6.0),
('Lateral Raise','strength','{"side_delts"}'::text[],'{"traps"}'::text[],'{"dumbbells"}'::text[],'beginner','lateralRaise',3.0),
('Front Raise','strength','{"front_delts"}'::text[],'{"core"}'::text[],'{"dumbbells"}'::text[],'beginner','lateralRaise',3.0),
('Face Pull','strength','{"rear_delts","rhomboids"}'::text[],'{"rotator_cuff"}'::text[],'{"cable"}'::text[],'beginner','lateralRaise',3.5),
('Forward Lunge','strength','{"quads","glutes"}'::text[],'{"hamstrings","calves","core"}'::text[],'{}'::text[],'beginner','lunge',4.5),
('Reverse Lunge','strength','{"quads","glutes"}'::text[],'{"hamstrings"}'::text[],'{}'::text[],'beginner','lunge',4.5),
('Bulgarian Split Squat','strength','{"quads","glutes"}'::text[],'{"hamstrings","core"}'::text[],'{"dumbbells","bench"}'::text[],'intermediate','lunge',5.5),
('Leg Press','strength','{"quads","glutes"}'::text[],'{"hamstrings"}'::text[],'{"leg_press"}'::text[],'beginner','squat',5.0),
('Leg Curl','strength','{"hamstrings"}'::text[],'{}'::text[],'{"leg_curl"}'::text[],'beginner','deadlift',3.5),
('Standing Calf Raise','strength','{"calves"}'::text[],'{}'::text[],'{}'::text[],'beginner','calfRaise',3.0),
('Wall Sit','strength','{"quads"}'::text[],'{"glutes","core"}'::text[],'{}'::text[],'beginner','squat',4.0),
('Push-up','strength','{"chest","triceps"}'::text[],'{"front_delts","core"}'::text[],'{}'::text[],'beginner','pushup',5.5),
('Wide Push-up','strength','{"chest"}'::text[],'{"triceps","front_delts"}'::text[],'{}'::text[],'beginner','pushup',5.5),
('Diamond Push-up','strength','{"triceps","inner_chest"}'::text[],'{"core"}'::text[],'{}'::text[],'intermediate','pushup',6.0),
('Pike Push-up','strength','{"front_delts"}'::text[],'{"triceps"}'::text[],'{}'::text[],'beginner','pushup',5.0),
('Inverted Row','strength','{"lats","rhomboids"}'::text[],'{"biceps","rear_delts"}'::text[],'{"barbell","rack"}'::text[],'beginner','pullup',5.5),
('Plank','core','{"core","transverse_abdominis"}'::text[],'{"shoulders","glutes"}'::text[],'{}'::text[],'beginner','plank',3.5),
('Side Plank','core','{"obliques","core"}'::text[],'{"glutes","shoulders"}'::text[],'{}'::text[],'beginner','plank',3.5),
('Crunch','core','{"upper_abs"}'::text[],'{}'::text[],'{}'::text[],'beginner','crunch',3.5),
('Bicycle Crunch','core','{"obliques","upper_abs"}'::text[],'{}'::text[],'{}'::text[],'beginner','crunch',4.5),
('Lying Leg Raise','core','{"lower_abs","hip_flexors"}'::text[],'{"core"}'::text[],'{}'::text[],'beginner','legRaise',4.0),
('Hanging Leg Raise','core','{"lower_abs","hip_flexors"}'::text[],'{"lats","core"}'::text[],'{"pullup_bar"}'::text[],'intermediate','legRaise',5.5),
('Russian Twist','core','{"obliques"}'::text[],'{"core"}'::text[],'{}'::text[],'beginner','russianTwist',4.0),
('Ab Wheel Rollout','core','{"core","transverse_abdominis"}'::text[],'{"lats","shoulders"}'::text[],'{"ab_wheel"}'::text[],'intermediate','plank',5.0),
('Dead Bug','core','{"core","transverse_abdominis"}'::text[],'{"hip_flexors"}'::text[],'{}'::text[],'beginner','legRaise',3.0),
('Burpee','hiit','{"full_body"}'::text[],'{}'::text[],'{}'::text[],'intermediate','burpee',10.0),
('Jumping Jack','cardio','{"full_body"}'::text[],'{}'::text[],'{}'::text[],'beginner','jumpingJack',7.0),
('High Knees','cardio','{"hip_flexors","calves"}'::text[],'{"core"}'::text[],'{}'::text[],'beginner','highKnees',8.0),
('Mountain Climber','hiit','{"core","hip_flexors"}'::text[],'{"shoulders","quads"}'::text[],'{}'::text[],'beginner','mountainClimber',8.0),
('Box Jump','hiit','{"quads","glutes"}'::text[],'{"calves","core"}'::text[],'{"plyo_box"}'::text[],'intermediate','squat',10.0),
('Jump Squat','hiit','{"quads","glutes"}'::text[],'{"calves","core"}'::text[],'{}'::text[],'intermediate','squat',9.0),
('Sprint (Treadmill)','cardio','{"quads","hamstrings"}'::text[],'{"glutes","calves","core"}'::text[],'{"treadmill"}'::text[],'intermediate','highKnees',14.0),
('Rowing Machine','cardio','{"back","legs"}'::text[],'{"core","arms"}'::text[],'{"rowing_machine"}'::text[],'beginner','pullup',7.0),
('Cycling','cardio','{"quads","hamstrings"}'::text[],'{"calves","glutes"}'::text[],'{"cycle_machine"}'::text[],'beginner','squat',8.0),
('Jump Rope','cardio','{"calves","shoulders"}'::text[],'{"core","coordination"}'::text[],'{"jump_rope"}'::text[],'beginner','jumpingJack',12.0),
('Hip Flexor Stretch','flexibility','{"hip_flexors"}'::text[],'{}'::text[],'{}'::text[],'beginner','lunge',2.0),
('Hamstring Stretch','flexibility','{"hamstrings"}'::text[],'{}'::text[],'{}'::text[],'beginner','deadlift',2.0),
('Pigeon Pose','flexibility','{"glutes","hip_flexors"}'::text[],'{}'::text[],'{}'::text[],'beginner','lunge',2.0),
('Child''s Pose','flexibility','{"lower_back","lats"}'::text[],'{}'::text[],'{}'::text[],'beginner','plank',1.5),
('Foam Roll Quads','recovery','{"quads"}'::text[],'{}'::text[],'{"foam_roller"}'::text[],'beginner','plank',2.5),
('Foam Roll IT Band','recovery','{"it_band"}'::text[],'{"outer_quads"}'::text[],'{"foam_roller"}'::text[],'beginner','plank',2.5),
('Box Step-up','sport','{"quads","glutes"}'::text[],'{"calves","core"}'::text[],'{"plyo_box"}'::text[],'beginner','lunge',5.5),
('Broad Jump','sport','{"quads","glutes","calves"}'::text[],'{"core"}'::text[],'{}'::text[],'intermediate','squat',9.0),
('Lateral Bound','sport','{"glutes","adductors"}'::text[],'{"calves","core"}'::text[],'{}'::text[],'intermediate','jumpingJack',8.0),
('Medicine Ball Slam','sport','{"core","shoulders"}'::text[],'{"triceps","lats"}'::text[],'{"medicine_ball"}'::text[],'intermediate','shoulderPress',8.5)
on conflict (lower(name)) do update set
  category = excluded.category,
  muscle_primary = excluded.muscle_primary,
  muscle_secondary = excluded.muscle_secondary,
  equipment_required = excluded.equipment_required,
  difficulty = excluded.difficulty,
  animation_key = excluded.animation_key,
  met = excluded.met,
  updated_at = now();