import type { ExerciseConfig, FormError, FormRule } from "../types";

const buildRule = (id: string, check: FormRule["check"], error: Omit<FormError, "id">): FormRule => ({
  id,
  check,
  error: {
    id,
    ...error,
  },
});

export const exerciseRegistry: ExerciseConfig[] = [
  {
    id: "squat",
    name: "Squat",
    category: "strength",
    cameraPosition: "side_or_front",
    idealDistance: [1.5, 2.5],
    primaryAngleKey: "leftKneeAngle",
    repThresholds: { topAngleRange: [160, 180], bottomAngleRange: [60, 100] },
    formRules: [
      buildRule("knee_cave", (a, phase) => (phase === "down" || phase === "bottom") && (a.leftKneeOverToe > 0.04 || a.rightKneeOverToe > 0.04), {
        severity: "critical",
        joint: "LEFT_KNEE",
        message: "Your knees are caving in. Drive them out over your toes.",
        cue: "Knees out",
        fix: "Push your knees outward in the direction of your pinky toes.",
        minDuration: 400,
      }),
      buildRule("no_depth", (a, phase) => phase === "bottom" && a.leftKneeAngle > 110 && a.rightKneeAngle > 110, {
        severity: "warning",
        joint: "LEFT_KNEE",
        message: "Go deeper. Hip crease should be below your knees.",
        cue: "Go deeper",
        fix: "Lower until your hip crease passes below your knee line.",
        minDuration: 500,
      }),
      buildRule("forward_lean", (a, phase) => (phase === "down" || phase === "bottom") && a.torsoLeanAngle > 45, {
        severity: "warning",
        joint: "torso",
        message: "Chest is dropping. Keep your torso more upright.",
        cue: "Chest up",
        fix: "Keep your chest proud and the upper back tight.",
        minDuration: 400,
      }),
      buildRule("uneven_hips", (a) => a.hipLevelDiff > 0.05, {
        severity: "warning",
        joint: "hips",
        message: "Your hips are shifting to one side. Keep them level.",
        cue: "Level hips",
        fix: "Distribute pressure evenly through both feet.",
        minDuration: 600,
      }),
      buildRule("heels_rising", (a, phase) => (phase === "down" || phase === "bottom") && (a.leftAnkleAngle < 60 || a.rightAnkleAngle < 60), {
        severity: "critical",
        joint: "LEFT_ANKLE",
        message: "Heels are coming up. Drive through your heels.",
        cue: "Heels down",
        fix: "Keep full-foot pressure and sit between the hips.",
        minDuration: 400,
      }),
    ],
    phaseCues: {
      concentric: "Drive up through your heels.",
      eccentric: "Control the descent for three seconds.",
      top: "Full lockout. Hips and knees extended.",
      bottom: "Hold depth. Chest up.",
    },
    muscles: ["Quads", "Glutes", "Adductors"],
    cameraHeight: "Hip height",
    description: "Front or side setup to watch depth, knee tracking, and torso position.",
    setupNotes: ["Stand far enough back for your full body to fit in frame.", "Turn slightly if you want a cleaner side view."],
  },
  {
    id: "pushup",
    name: "Push-up",
    category: "strength",
    cameraPosition: "side",
    idealDistance: [1.5, 2.5],
    primaryAngleKey: "leftElbowAngle",
    repThresholds: { topAngleRange: [155, 180], bottomAngleRange: [60, 95] },
    formRules: [
      buildRule("hips_sagging", (a) => a.hipDrop > 0.04, {
        severity: "critical",
        joint: "hips",
        message: "Hips are sagging. Squeeze your core and glutes.",
        cue: "Core tight",
        fix: "Make your body one straight line from shoulder to heel.",
        minDuration: 350,
      }),
      buildRule("hips_piking", (a) => a.hipDrop < -0.04, {
        severity: "warning",
        joint: "hips",
        message: "Hips are too high. Lower them into a straight line.",
        cue: "Hips level",
        fix: "Think ribs down and glutes tight.",
        minDuration: 350,
      }),
      buildRule("elbow_flare", (a, phase) => (phase === "down" || phase === "bottom") && (a.leftShoulderAngle > 70 || a.rightShoulderAngle > 70), {
        severity: "warning",
        joint: "LEFT_ELBOW",
        message: "Elbows are flaring. Keep them at about forty-five degrees.",
        cue: "Elbows in",
        fix: "Screw your hands into the floor and tuck the elbows slightly.",
        minDuration: 500,
      }),
      buildRule("no_depth", (a, phase) => phase === "bottom" && a.leftElbowAngle > 110, {
        severity: "warning",
        joint: "LEFT_ELBOW",
        message: "Go lower. Chest should nearly touch the ground.",
        cue: "Go lower",
        fix: "Lower until the chest hovers just above the floor.",
        minDuration: 500,
      }),
    ],
    phaseCues: {
      concentric: "Push the floor away.",
      eccentric: "Lower with control.",
      top: "Arms long. Core braced.",
      bottom: "Chest low. Elbows forty-five.",
    },
    muscles: ["Chest", "Triceps", "Anterior delts"],
    cameraHeight: "Floor level",
    description: "Side view catches body line, elbow flare, and range of motion.",
    setupNotes: ["Place the phone low and side-on.", "Keep your full plank shape in frame."],
  },
  {
    id: "deadlift",
    name: "Deadlift",
    category: "strength",
    cameraPosition: "side",
    idealDistance: [1.5, 2.5],
    primaryAngleKey: "leftHipAngle",
    repThresholds: { topAngleRange: [155, 180], bottomAngleRange: [45, 90] },
    formRules: [
      buildRule("rounded_lower_back", (a, phase) => (phase === "down" || phase === "bottom") && a.torsoLeanAngle > 70, {
        severity: "critical",
        joint: "spine",
        message: "Lower back is rounding. Hinge at your hips and stay neutral.",
        cue: "Neutral spine",
        fix: "Keep the chest proud and lats tight as you hinge.",
        minDuration: 300,
      }),
      buildRule("hyperextension", (a, phase) => phase === "top" && a.torsoLeanAngle > 10, {
        severity: "warning",
        joint: "spine",
        message: "Avoid leaning back at the top. Stand tall, not past neutral.",
        cue: "Stand tall",
        fix: "Finish with glutes, not lumbar extension.",
        minDuration: 400,
      }),
      buildRule("bar_path", (a) => Math.abs(a.leftKneeOverToe) > 0.08, {
        severity: "warning",
        joint: "LEFT_KNEE",
        message: "Keep the bar close to your body throughout the lift.",
        cue: "Bar close",
        fix: "Let the bar trace your shins and thighs.",
        minDuration: 400,
      }),
    ],
    phaseCues: {
      concentric: "Drive the floor away.",
      eccentric: "Hinge first, then soften the knees.",
      top: "Stand tall with glutes locked.",
      bottom: "Bar over mid-foot. Spine neutral.",
    },
    muscles: ["Hamstrings", "Glutes", "Back"],
    cameraHeight: "Hip height",
    description: "Side view monitors spinal position and hinge quality.",
    setupNotes: ["Frame the full body and the floor around your feet.", "Keep the camera square to your side."],
  },
  {
    id: "lunge",
    name: "Lunge",
    category: "strength",
    cameraPosition: "front",
    idealDistance: [1.5, 2.5],
    primaryAngleKey: "leftKneeAngle",
    repThresholds: { topAngleRange: [155, 180], bottomAngleRange: [80, 105] },
    formRules: [
      buildRule("knee_over_toe", (a, phase) => phase === "bottom" && a.leftKneeOverToe > 0.06, {
        severity: "warning",
        joint: "LEFT_KNEE",
        message: "Front knee is too far forward. Step out a touch wider.",
        cue: "Longer stride",
        fix: "Take a slightly longer stride so the front shin stays more vertical.",
        minDuration: 400,
      }),
      buildRule("back_knee_drag", (a, phase) => phase === "bottom" && a.rightKneeAngle < 70, {
        severity: "info",
        joint: "RIGHT_KNEE",
        message: "Lower the back knee closer to the floor for full range.",
        cue: "Lower back knee",
        fix: "Aim for the back knee to hover just above the ground.",
        minDuration: 500,
      }),
      buildRule("torso_lean", (a) => a.torsoLeanAngle > 20, {
        severity: "warning",
        joint: "torso",
        message: "Keep your torso upright. Do not fold forward.",
        cue: "Stay upright",
        fix: "Stack ribs over hips and brace the core.",
        minDuration: 400,
      }),
    ],
    phaseCues: {
      concentric: "Push through the front heel.",
      eccentric: "Step and lower with control.",
      top: "Stand tall and balanced.",
      bottom: "Find ninety-ninety.",
    },
    muscles: ["Quads", "Glutes", "Adductors"],
    cameraHeight: "Hip height",
    description: "Front setup helps Mo catch stride length and hip shift.",
    setupNotes: ["Give yourself enough room to step forward.", "Keep both feet fully visible."],
  },
  {
    id: "shoulder_press",
    name: "Shoulder Press",
    category: "strength",
    cameraPosition: "front",
    idealDistance: [1.5, 2.5],
    primaryAngleKey: "leftElbowAngle",
    repThresholds: { topAngleRange: [155, 180], bottomAngleRange: [75, 100] },
    formRules: [
      buildRule("lower_back_arch", (a, phase) => (phase === "up" || phase === "top") && a.torsoLeanAngle > 15, {
        severity: "critical",
        joint: "spine",
        message: "You are arching your lower back. Brace your core.",
        cue: "Brace core",
        fix: "Tuck the ribs down and squeeze the glutes.",
        minDuration: 300,
      }),
      buildRule("uneven_press", (a) => Math.abs(a.leftElbowAngle - a.rightElbowAngle) > 20 || a.handHeightDiff > 0.05, {
        severity: "warning",
        joint: "LEFT_ELBOW",
        message: "One arm is leading. Press evenly with both arms.",
        cue: "Even press",
        fix: "Drive both hands overhead at the same speed.",
        minDuration: 500,
      }),
    ],
    phaseCues: {
      concentric: "Press overhead with a braced core.",
      eccentric: "Lower slowly and stay stacked.",
      top: "Arms locked. Ribs down.",
      bottom: "Wrists over elbows.",
    },
    muscles: ["Shoulders", "Triceps", "Upper chest"],
    cameraHeight: "Shoulder height",
    description: "Front view helps balance both arms and torso position.",
    setupNotes: ["Place the phone at shoulder level.", "Stay centered so both arms stay visible overhead."],
  },
  {
    id: "bicep_curl",
    name: "Bicep Curl",
    category: "strength",
    cameraPosition: "side",
    idealDistance: [1, 2],
    primaryAngleKey: "rightElbowAngle",
    repThresholds: { topAngleRange: [30, 70], bottomAngleRange: [150, 175] },
    formRules: [
      buildRule("elbow_swing", (a) => a.rightShoulderAngle > 35, {
        severity: "critical",
        joint: "RIGHT_SHOULDER",
        message: "Your elbows are swinging. Pin them to your sides.",
        cue: "Elbows still",
        fix: "Keep the upper arm still and only move the forearm.",
        minDuration: 400,
      }),
      buildRule("momentum", (a, phase) => phase === "down" && a.torsoLeanAngle > 15, {
        severity: "warning",
        joint: "torso",
        message: "You are using momentum. Slow the rep down.",
        cue: "No swinging",
        fix: "Control the lowering for two to three seconds.",
        minDuration: 400,
      }),
    ],
    phaseCues: {
      concentric: "Curl and squeeze at the top.",
      eccentric: "Lower all the way down.",
      top: "Peak squeeze.",
      bottom: "Full extension without resting.",
    },
    muscles: ["Biceps", "Forearms"],
    cameraHeight: "Hip height",
    description: "Side view checks torso swing and elbow travel.",
    setupNotes: ["Frame from head to knee.", "Stand side-on to the camera."],
  },
  {
    id: "plank",
    name: "Plank",
    category: "core",
    cameraPosition: "side",
    idealDistance: [1.5, 2.5],
    primaryAngleKey: "bodyLineAngle",
    repThresholds: { topAngleRange: [-8, 8], bottomAngleRange: [-8, 8] },
    formRules: [
      buildRule("hips_up", (a) => a.hipDrop < -0.04, {
        severity: "critical",
        joint: "hips",
        message: "Hips are too high. Lower to a flat line.",
        cue: "Hips down",
        fix: "Drop the hips until you make one straight line.",
        minDuration: 400,
      }),
      buildRule("hips_sagging", (a) => a.hipDrop > 0.04, {
        severity: "critical",
        joint: "hips",
        message: "Hips are sagging. Squeeze your core and glutes.",
        cue: "Core tight",
        fix: "Brace every muscle and hold a rigid line.",
        minDuration: 400,
      }),
    ],
    phaseCues: {
      concentric: "Hold and breathe steadily.",
      eccentric: "Hold and breathe steadily.",
      top: "Excellent line. Maintain it.",
      bottom: "Excellent line. Maintain it.",
    },
    muscles: ["Abs", "Obliques", "Glutes"],
    cameraHeight: "Floor level",
    description: "Side view keeps the body line honest during holds.",
    setupNotes: ["Put the phone near the floor.", "Keep your shoulders and heels visible."],
  },
  {
    id: "hip_thrust",
    name: "Hip Thrust",
    category: "strength",
    cameraPosition: "side",
    idealDistance: [1.5, 2.5],
    primaryAngleKey: "leftHipAngle",
    repThresholds: { topAngleRange: [155, 180], bottomAngleRange: [60, 100] },
    formRules: [
      buildRule("hyperextension", (a, phase) => phase === "top" && a.torsoLeanAngle > 10, {
        severity: "warning",
        joint: "spine",
        message: "Do not hyperextend your back at the top. Stop at neutral.",
        cue: "Neutral back",
        fix: "Finish with glutes and keep the ribs tucked down.",
        minDuration: 400,
      }),
      buildRule("knee_cave", (a) => a.leftKneeOverToe > 0.05 || a.rightKneeOverToe > 0.05, {
        severity: "warning",
        joint: "LEFT_KNEE",
        message: "Knees are caving in. Drive them apart.",
        cue: "Knees out",
        fix: "Press the knees out as you squeeze the glutes.",
        minDuration: 400,
      }),
    ],
    phaseCues: {
      concentric: "Drive hips up and squeeze.",
      eccentric: "Lower under control.",
      top: "Full extension. Glutes hard.",
      bottom: "Reset and build tension.",
    },
    muscles: ["Glutes", "Hamstrings"],
    cameraHeight: "Bench height",
    description: "Side view catches back extension and knee tracking.",
    setupNotes: ["Keep the bench and your feet in frame.", "Set the camera at hip height."],
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    category: "strength",
    cameraPosition: "side",
    idealDistance: [1.5, 2.5],
    primaryAngleKey: "leftHipAngle",
    repThresholds: { topAngleRange: [150, 180], bottomAngleRange: [55, 95] },
    formRules: [
      buildRule("rounded_back", (a, phase) => (phase === "down" || phase === "bottom") && a.torsoLeanAngle > 65, {
        severity: "critical",
        joint: "spine",
        message: "Back is rounding. Keep the hinge long and neutral.",
        cue: "Long spine",
        fix: "Push the hips back and keep the chest open.",
        minDuration: 300,
      }),
      buildRule("soft_knees", (a) => a.leftKneeAngle < 130, {
        severity: "warning",
        joint: "LEFT_KNEE",
        message: "Too much knee bend. Keep the movement hip-dominant.",
        cue: "Softer knees",
        fix: "Unlock the knees slightly and keep them fixed.",
        minDuration: 350,
      }),
    ],
    phaseCues: {
      concentric: "Drive hips through.",
      eccentric: "Hinge back and feel the hamstrings.",
      top: "Stand tall without leaning back.",
      bottom: "Stretch, then reverse.",
    },
    muscles: ["Hamstrings", "Glutes", "Back"],
    cameraHeight: "Hip height",
    description: "Side view focuses on hinge mechanics and spinal control.",
    setupNotes: ["Square the camera to your side.", "Leave room to see the bar path."],
  },
  {
    id: "pull_up",
    name: "Pull-up",
    category: "strength",
    cameraPosition: "side",
    idealDistance: [1.5, 2.5],
    primaryAngleKey: "leftElbowAngle",
    repThresholds: { topAngleRange: [45, 85], bottomAngleRange: [150, 180] },
    formRules: [
      buildRule("short_range", (a, phase) => phase === "top" && a.leftElbowAngle > 95, {
        severity: "warning",
        joint: "LEFT_ELBOW",
        message: "You are cutting the range short. Pull higher.",
        cue: "Higher chest",
        fix: "Drive the chest toward the bar and finish the pull.",
        minDuration: 400,
      }),
      buildRule("kipping", (a) => a.torsoLeanAngle > 30, {
        severity: "warning",
        joint: "torso",
        message: "Too much swing. Keep the pull-up tighter.",
        cue: "Less swing",
        fix: "Brace the abs and pause briefly between reps.",
        minDuration: 400,
      }),
    ],
    phaseCues: {
      concentric: "Lead with the chest.",
      eccentric: "Lower under control.",
      top: "Chest tall at the top.",
      bottom: "Full hang without losing tension.",
    },
    muscles: ["Lats", "Biceps", "Mid-back"],
    cameraHeight: "Chest height",
    description: "Side view reveals body swing and depth at the hang.",
    setupNotes: ["Set the phone back far enough to see the full hang.", "Keep the bar and feet in frame."],
  },
  {
    id: "tricep_dip",
    name: "Tricep Dip",
    category: "strength",
    cameraPosition: "side",
    idealDistance: [1, 2],
    primaryAngleKey: "leftElbowAngle",
    repThresholds: { topAngleRange: [150, 180], bottomAngleRange: [60, 95] },
    formRules: [
      buildRule("shoulder_dump", (a) => a.leftShoulderAngle > 85, {
        severity: "critical",
        joint: "LEFT_SHOULDER",
        message: "Shoulders are dumping forward. Keep the chest open.",
        cue: "Chest open",
        fix: "Pull the shoulders down and back before each rep.",
        minDuration: 350,
      }),
      buildRule("short_depth", (a, phase) => phase === "bottom" && a.leftElbowAngle > 105, {
        severity: "warning",
        joint: "LEFT_ELBOW",
        message: "Go deeper if your shoulders tolerate it.",
        cue: "More depth",
        fix: "Lower until the elbow reaches roughly ninety degrees.",
        minDuration: 450,
      }),
    ],
    phaseCues: {
      concentric: "Press tall without shrugging.",
      eccentric: "Lower with control.",
      top: "Arms long and shoulders packed.",
      bottom: "Elbows bent, chest open.",
    },
    muscles: ["Triceps", "Chest", "Front delts"],
    cameraHeight: "Bench height",
    description: "Side view helps Mo track elbow depth and shoulder position.",
    setupNotes: ["Keep the bench or box visible.", "Frame your shoulders and heels."],
  },
  {
    id: "lateral_raise",
    name: "Lateral Raise",
    category: "strength",
    cameraPosition: "front",
    idealDistance: [1, 2],
    primaryAngleKey: "leftShoulderAngle",
    repThresholds: { topAngleRange: [80, 115], bottomAngleRange: [10, 35] },
    formRules: [
      buildRule("shrugging", (a) => a.shoulderLevelDiff > 0.04, {
        severity: "warning",
        joint: "LEFT_SHOULDER",
        message: "Do not shrug into the rep. Keep the traps quiet.",
        cue: "No shrug",
        fix: "Reach the hands out, not up, and keep the neck long.",
        minDuration: 400,
      }),
      buildRule("momentum", (a, phase) => phase === "up" && a.torsoLeanAngle > 12, {
        severity: "warning",
        joint: "torso",
        message: "Too much body swing. Slow the raise down.",
        cue: "Still torso",
        fix: "Soften the knees and move only the arms.",
        minDuration: 350,
      }),
    ],
    phaseCues: {
      concentric: "Lift wide with soft elbows.",
      eccentric: "Lower slowly.",
      top: "Hands just below shoulder height.",
      bottom: "Reset without swinging.",
    },
    muscles: ["Side delts", "Upper traps"],
    cameraHeight: "Shoulder height",
    description: "Front view keeps both shoulders and hands visible.",
    setupNotes: ["Center yourself so both arms stay inside frame.", "Keep the phone at chest or shoulder height."],
  },
  {
    id: "russian_twist",
    name: "Russian Twist",
    category: "core",
    cameraPosition: "front",
    idealDistance: [1, 2],
    primaryAngleKey: "wristDistance",
    repThresholds: { topAngleRange: [0.35, 0.75], bottomAngleRange: [0.1, 0.34] },
    formRules: [
      buildRule("torso_collapse", (a) => a.torsoLeanAngle > 45, {
        severity: "warning",
        joint: "torso",
        message: "You are collapsing through the torso. Stay tall through the chest.",
        cue: "Tall torso",
        fix: "Lean back slightly, then rotate from the ribs.",
        minDuration: 350,
      }),
      buildRule("arms_only", (a) => a.shoulderLevelDiff < 0.01 && a.wristDistance > 0.55, {
        severity: "info",
        joint: "torso",
        message: "Rotate the torso, not just the hands.",
        cue: "Rotate ribs",
        fix: "Move your sternum with the hands every rep.",
        minDuration: 500,
      }),
    ],
    phaseCues: {
      concentric: "Rotate through the ribs.",
      eccentric: "Move side to side with control.",
      top: "Stay braced and breathe.",
      bottom: "Stay braced and breathe.",
    },
    muscles: ["Obliques", "Abs"],
    cameraHeight: "Hip height",
    description: "Front view tracks symmetry during rotational core work.",
    setupNotes: ["Sit far enough back to show your full torso.", "Keep both hands visible at the edges of each twist."],
  },
  {
    id: "leg_raise",
    name: "Leg Raise",
    category: "core",
    cameraPosition: "side",
    idealDistance: [1, 2],
    primaryAngleKey: "leftHipAngle",
    repThresholds: { topAngleRange: [55, 95], bottomAngleRange: [145, 180] },
    formRules: [
      buildRule("lower_back_arch", (a) => a.hipDrop > 0.03, {
        severity: "critical",
        joint: "spine",
        message: "Lower back is arching off the floor. Brace harder.",
        cue: "Ribs down",
        fix: "Posteriorly tilt the pelvis and move slower.",
        minDuration: 300,
      }),
      buildRule("short_lower", (a, phase) => phase === "bottom" && a.leftHipAngle < 135, {
        severity: "warning",
        joint: "LEFT_HIP",
        message: "Lower further for full range if you can keep control.",
        cue: "More range",
        fix: "Reach the heels long and control the descent.",
        minDuration: 400,
      }),
    ],
    phaseCues: {
      concentric: "Lift with the lower abs.",
      eccentric: "Lower slowly and keep the back pinned.",
      top: "Feet high, core locked.",
      bottom: "Hover without losing tension.",
    },
    muscles: ["Lower abs", "Hip flexors"],
    cameraHeight: "Floor level",
    description: "Side view catches pelvic position on the floor.",
    setupNotes: ["Keep the phone low and side-on.", "Show your full body from shoulders to feet."],
  },
  {
    id: "crunch",
    name: "Crunch",
    category: "core",
    cameraPosition: "side",
    idealDistance: [1, 2],
    primaryAngleKey: "leftHipAngle",
    repThresholds: { topAngleRange: [55, 95], bottomAngleRange: [145, 180] },
    formRules: [
      buildRule("neck_pull", (a) => a.torsoLeanAngle > 55, {
        severity: "warning",
        joint: "torso",
        message: "Do not yank with the neck. Curl through the ribs.",
        cue: "Curl ribs",
        fix: "Keep the chin gently tucked and lead with the sternum.",
        minDuration: 350,
      }),
      buildRule("short_range", (a, phase) => phase === "top" && a.leftHipAngle > 110, {
        severity: "info",
        joint: "torso",
        message: "Curl a little higher before lowering.",
        cue: "Higher curl",
        fix: "Exhale hard and round through the upper abs.",
        minDuration: 500,
      }),
    ],
    phaseCues: {
      concentric: "Exhale and curl up.",
      eccentric: "Lower one vertebra at a time.",
      top: "Squeeze the abs.",
      bottom: "Stay braced between reps.",
    },
    muscles: ["Upper abs"],
    cameraHeight: "Floor level",
    description: "Side view helps separate spinal flexion from neck pulling.",
    setupNotes: ["Place the phone low to the floor.", "Keep your torso and knees fully visible."],
  },
  {
    id: "burpee",
    name: "Burpee",
    category: "cardio",
    cameraPosition: "side_or_front",
    idealDistance: [2, 3],
    primaryAngleKey: "leftKneeAngle",
    repThresholds: { topAngleRange: [150, 180], bottomAngleRange: [55, 100] },
    formRules: [
      buildRule("soft_plank", (a) => a.hipDrop > 0.05, {
        severity: "critical",
        joint: "spine",
        message: "Your plank position is breaking. Brace harder on the floor.",
        cue: "Rigid plank",
        fix: "Hit a strong plank before snapping the feet back in.",
        minDuration: 250,
      }),
      buildRule("lazy_jump", (a, phase) => phase === "top" && a.torsoLeanAngle > 20, {
        severity: "info",
        joint: "torso",
        message: "Finish tall at the top so the rep counts cleanly.",
        cue: "Stand tall",
        fix: "Reach tall and reset before dropping again.",
        minDuration: 350,
      }),
    ],
    phaseCues: {
      concentric: "Explode up.",
      eccentric: "Move crisply but stay tight.",
      top: "Stand tall before the next rep.",
      bottom: "Hit a strong plank.",
    },
    muscles: ["Full body", "Conditioning"],
    cameraHeight: "Hip height",
    description: "A wider frame keeps the whole burpee sequence visible.",
    setupNotes: ["Step farther back than you think.", "Leave extra space above your head."],
  },
  {
    id: "mountain_climber",
    name: "Mountain Climber",
    category: "cardio",
    cameraPosition: "side",
    idealDistance: [1.5, 2.5],
    primaryAngleKey: "leftHipAngle",
    repThresholds: { topAngleRange: [70, 105], bottomAngleRange: [145, 180] },
    formRules: [
      buildRule("hips_bouncing", (a) => Math.abs(a.hipDrop) > 0.05, {
        severity: "warning",
        joint: "hips",
        message: "Keep the hips steadier. Do not bounce through the plank.",
        cue: "Steady hips",
        fix: "Slow the tempo until the torso stays quiet.",
        minDuration: 250,
      }),
      buildRule("short_drive", (a, phase) => phase === "top" && a.leftHipAngle > 120, {
        severity: "info",
        joint: "LEFT_HIP",
        message: "Drive the knee higher toward the chest.",
        cue: "Knee higher",
        fix: "Pull the knee further forward each rep.",
        minDuration: 300,
      }),
    ],
    phaseCues: {
      concentric: "Drive the knee under the chest.",
      eccentric: "Snap the leg back to plank.",
      top: "Shoulders over wrists.",
      bottom: "Keep the body long.",
    },
    muscles: ["Core", "Shoulders", "Hip flexors"],
    cameraHeight: "Floor level",
    description: "Side view exposes hip bounce and knee drive.",
    setupNotes: ["Keep the phone low to the ground.", "Show your whole plank line."],
  },
  {
    id: "calf_raise",
    name: "Calf Raise",
    category: "strength",
    cameraPosition: "side",
    idealDistance: [1, 2],
    primaryAngleKey: "leftAnkleAngle",
    repThresholds: { topAngleRange: [90, 135], bottomAngleRange: [45, 85] },
    formRules: [
      buildRule("ankle_roll", (a) => a.hipLevelDiff > 0.04, {
        severity: "warning",
        joint: "LEFT_ANKLE",
        message: "You are shifting side to side. Stay centered over the foot.",
        cue: "Stay centered",
        fix: "Press through the big toe and second toe evenly.",
        minDuration: 350,
      }),
      buildRule("short_peak", (a, phase) => phase === "top" && a.leftAnkleAngle < 95, {
        severity: "info",
        joint: "LEFT_ANKLE",
        message: "Push higher onto the toes at the top.",
        cue: "Higher rise",
        fix: "Pause at the top and reach taller through the ankles.",
        minDuration: 400,
      }),
    ],
    phaseCues: {
      concentric: "Rise straight up through the toes.",
      eccentric: "Lower slowly and feel the stretch.",
      top: "Pause high.",
      bottom: "Control the heel drop.",
    },
    muscles: ["Calves"],
    cameraHeight: "Hip height",
    description: "Side view tracks ankle travel and balance on the foot.",
    setupNotes: ["Frame from head to foot.", "Stand side-on for a clearer ankle view."],
  },
];

export const exerciseLookup = Object.fromEntries(exerciseRegistry.map((exercise) => [exercise.id, exercise])) as Record<
  string,
  ExerciseConfig
>;

export const defaultExerciseConfig = exerciseLookup.squat;
