import { createAnimation } from "./shared";

export const benchPressAnimation = createAnimation(
  "Bench Press",
  2250,
  [
    {
      t: 0,
      torso: { rotate: 62, translateX: -2, translateY: 46 },
      upperArmL: { rotate: 98, translateX: 8, translateY: 28 },
      foreArmL: { rotate: 64, translateX: 8, translateY: 20 },
      upperArmR: { rotate: -98, translateX: -8, translateY: 28 },
      foreArmR: { rotate: -64, translateX: -8, translateY: 20 },
      thighL: { rotate: -10, translateX: -2, translateY: 8 },
      thighR: { rotate: -10, translateX: 2, translateY: 8 },
    },
    {
      t: 0.32,
      torso: { rotate: 64, translateX: -2, translateY: 49 },
      upperArmL: { rotate: 86, translateX: 7, translateY: 34 },
      foreArmL: { rotate: 82, translateX: 7, translateY: 27 },
      upperArmR: { rotate: -86, translateX: -7, translateY: 34 },
      foreArmR: { rotate: -82, translateX: -7, translateY: 27 },
      thighL: { rotate: -11, translateX: -2, translateY: 9 },
      thighR: { rotate: -11, translateX: 2, translateY: 9 },
    },
    {
      t: 0.56,
      torso: { rotate: 66, translateX: -2, translateY: 52 },
      upperArmL: { rotate: 76, translateX: 6, translateY: 36 },
      foreArmL: { rotate: 94, translateX: 7, translateY: 30 },
      upperArmR: { rotate: -76, translateX: -6, translateY: 36 },
      foreArmR: { rotate: -94, translateX: -7, translateY: 30 },
      thighL: { rotate: -12, translateX: -2, translateY: 10 },
      thighR: { rotate: -12, translateX: 2, translateY: 10 },
    },
    {
      t: 0.66,
      torso: { rotate: 66, translateX: -2, translateY: 52 },
      upperArmL: { rotate: 76, translateX: 6, translateY: 36 },
      foreArmL: { rotate: 94, translateX: 7, translateY: 30 },
      upperArmR: { rotate: -76, translateX: -6, translateY: 36 },
      foreArmR: { rotate: -94, translateX: -7, translateY: 30 },
      thighL: { rotate: -12, translateX: -2, translateY: 10 },
      thighR: { rotate: -12, translateX: 2, translateY: 10 },
    },
    {
      t: 0.9,
      torso: { rotate: 63, translateX: -2, translateY: 47 },
      upperArmL: { rotate: 94, translateX: 8, translateY: 30 },
      foreArmL: { rotate: 70, translateX: 8, translateY: 23 },
      upperArmR: { rotate: -94, translateX: -8, translateY: 30 },
      foreArmR: { rotate: -70, translateX: -8, translateY: 23 },
      thighL: { rotate: -10, translateX: -2, translateY: 8 },
      thighR: { rotate: -10, translateX: 2, translateY: 8 },
    },
    {
      t: 1,
      torso: { rotate: 62, translateX: -2, translateY: 46 },
      upperArmL: { rotate: 98, translateX: 8, translateY: 28 },
      foreArmL: { rotate: 64, translateX: 8, translateY: 20 },
      upperArmR: { rotate: -98, translateX: -8, translateY: 28 },
      foreArmR: { rotate: -64, translateX: -8, translateY: 20 },
      thighL: { rotate: -10, translateX: -2, translateY: 8 },
      thighR: { rotate: -10, translateX: 2, translateY: 8 },
    },
  ],
  ["Shoulder blades packed", "Touch lower chest", "Press with stable wrists"],
  {
    phase: "concentric",
    repPhases: {
      eccentric: { start: 0, end: 0.56, label: "Lower bar to chest line" },
      isometric: { start: 0.56, end: 0.66, label: "Pause tight" },
      concentric: { start: 0.66, end: 1, label: "Press to lockout" },
    },
    style: {
      interpolation: "smoothstep",
      transitionMs: 220,
      shadowPulse: 1.1,
    },
  },
);
