import { createAnimation } from "./shared";

export const burpeeAnimation = createAnimation(
  "Burpee",
  2850,
  [
    {
      t: 0,
      torso: { rotate: 0, translateX: 0, translateY: 0 },
      thighL: { rotate: 0, translateX: 0, translateY: 0 },
      thighR: { rotate: 0, translateX: 0, translateY: 0 },
      upperArmL: { rotate: 10, translateX: 0, translateY: 0 },
      upperArmR: { rotate: -10, translateX: 0, translateY: 0 },
    },
    {
      t: 0.18,
      torso: { rotate: 28, translateX: 0, translateY: 30 },
      thighL: { rotate: -70, translateX: -2, translateY: 18 },
      thighR: { rotate: -70, translateX: 2, translateY: 18 },
      shinL: { rotate: 72, translateX: -1, translateY: 20 },
      shinR: { rotate: 72, translateX: 1, translateY: 20 },
      upperArmL: { rotate: 45, translateX: 4, translateY: 20 },
      upperArmR: { rotate: -45, translateX: -4, translateY: 20 },
    },
    {
      t: 0.42,
      torso: { rotate: 60, translateX: -2, translateY: 40 },
      thighL: { rotate: -14, translateX: -3, translateY: 10 },
      thighR: { rotate: -14, translateX: 3, translateY: 10 },
      upperArmL: { rotate: 85, translateX: 8, translateY: 32 },
      upperArmR: { rotate: -85, translateX: -8, translateY: 32 },
      foreArmL: { rotate: 30, translateX: 9, translateY: 34 },
      foreArmR: { rotate: -30, translateX: -9, translateY: 34 },
    },
    {
      t: 0.64,
      torso: { rotate: 22, translateX: 0, translateY: 22 },
      thighL: { rotate: -58, translateX: -2, translateY: 16 },
      thighR: { rotate: -58, translateX: 2, translateY: 16 },
      shinL: { rotate: 58, translateX: -1, translateY: 18 },
      shinR: { rotate: 58, translateX: 1, translateY: 18 },
      upperArmL: { rotate: 38, translateX: 3, translateY: 14 },
      upperArmR: { rotate: -38, translateX: -3, translateY: 14 },
    },
    {
      t: 0.82,
      torso: { rotate: -6, translateX: 0, translateY: -8 },
      head: { rotate: 0, translateX: 0, translateY: -8 },
      upperArmL: { rotate: 148, translateX: 4, translateY: -8 },
      upperArmR: { rotate: -148, translateX: -4, translateY: -8 },
      thighL: { rotate: -6, translateX: -1, translateY: -4 },
      thighR: { rotate: 6, translateX: 1, translateY: -4 },
      shinL: { rotate: 16, translateX: -1, translateY: -4 },
      shinR: { rotate: 16, translateX: 1, translateY: -4 },
    },
    {
      t: 0.92,
      torso: { rotate: -3, translateX: 0, translateY: -5 },
      head: { rotate: 0, translateX: 0, translateY: -5 },
      upperArmL: { rotate: 122, translateX: 3, translateY: -4 },
      upperArmR: { rotate: -122, translateX: -3, translateY: -4 },
      thighL: { rotate: -2, translateX: -1, translateY: -2 },
      thighR: { rotate: 2, translateX: 1, translateY: -2 },
      shinL: { rotate: 8, translateX: -1, translateY: -2 },
      shinR: { rotate: 8, translateX: 1, translateY: -2 },
    },
    {
      t: 1,
      torso: { rotate: 0, translateX: 0, translateY: 0 },
      thighL: { rotate: 0, translateX: 0, translateY: 0 },
      thighR: { rotate: 0, translateX: 0, translateY: 0 },
      upperArmL: { rotate: 10, translateX: 0, translateY: 0 },
      upperArmR: { rotate: -10, translateX: 0, translateY: 0 },
    },
  ],
  ["Drop quickly with control", "Snap feet in under hips", "Jump with full extension"],
  {
    phase: "concentric",
    repPhases: {
      eccentric: { start: 0, end: 0.42, label: "Drop and sprawl" },
      concentric: { start: 0.42, end: 0.82, label: "Snap in and jump" },
      rest: { start: 0.82, end: 1, label: "Reset landing" },
    },
    style: {
      interpolation: "sine",
      transitionMs: 260,
      shadowPulse: 1.45,
    },
  },
);
