import { createAnimation } from "./shared";

export const hipThrustAnimation = createAnimation(
  "Hip Thrust",
  2350,
  [
    {
      t: 0,
      torso: { rotate: 56, translateX: -2, translateY: 36 },
      thighL: { rotate: -60, translateX: -2, translateY: 26 },
      thighR: { rotate: -60, translateX: 2, translateY: 26 },
      shinL: { rotate: 80, translateX: -1, translateY: 24 },
      shinR: { rotate: 80, translateX: 1, translateY: 24 },
      upperArmL: { rotate: 42, translateX: 4, translateY: 16 },
      upperArmR: { rotate: -42, translateX: -4, translateY: 16 },
    },
    {
      t: 0.32,
      torso: { rotate: 42, translateX: -2, translateY: 24 },
      thighL: { rotate: -42, translateX: -2, translateY: 18 },
      thighR: { rotate: -42, translateX: 2, translateY: 18 },
      shinL: { rotate: 58, translateX: -1, translateY: 15 },
      shinR: { rotate: 58, translateX: 1, translateY: 15 },
      upperArmL: { rotate: 34, translateX: 3, translateY: 11 },
      upperArmR: { rotate: -34, translateX: -3, translateY: 11 },
    },
    {
      t: 0.56,
      torso: { rotate: 26, translateX: -2, translateY: 12 },
      thighL: { rotate: -22, translateX: -2, translateY: 8 },
      thighR: { rotate: -22, translateX: 2, translateY: 8 },
      shinL: { rotate: 40, translateX: -1, translateY: 8 },
      shinR: { rotate: 40, translateX: 1, translateY: 8 },
      upperArmL: { rotate: 30, translateX: 3, translateY: 8 },
      upperArmR: { rotate: -30, translateX: -3, translateY: 8 },
      head: { rotate: 0, translateX: 0, translateY: -4 },
    },
    {
      t: 0.7,
      torso: { rotate: 24, translateX: -2, translateY: 10 },
      thighL: { rotate: -20, translateX: -2, translateY: 7 },
      thighR: { rotate: -20, translateX: 2, translateY: 7 },
      shinL: { rotate: 38, translateX: -1, translateY: 7 },
      shinR: { rotate: 38, translateX: 1, translateY: 7 },
      upperArmL: { rotate: 30, translateX: 3, translateY: 8 },
      upperArmR: { rotate: -30, translateX: -3, translateY: 8 },
      head: { rotate: 0, translateX: 0, translateY: -4 },
    },
    {
      t: 0.9,
      torso: { rotate: 48, translateX: -2, translateY: 30 },
      thighL: { rotate: -50, translateX: -2, translateY: 22 },
      thighR: { rotate: -50, translateX: 2, translateY: 22 },
      shinL: { rotate: 70, translateX: -1, translateY: 20 },
      shinR: { rotate: 70, translateX: 1, translateY: 20 },
      upperArmL: { rotate: 38, translateX: 4, translateY: 14 },
      upperArmR: { rotate: -38, translateX: -4, translateY: 14 },
    },
    {
      t: 1,
      torso: { rotate: 56, translateX: -2, translateY: 36 },
      thighL: { rotate: -60, translateX: -2, translateY: 26 },
      thighR: { rotate: -60, translateX: 2, translateY: 26 },
      shinL: { rotate: 80, translateX: -1, translateY: 24 },
      shinR: { rotate: 80, translateX: 1, translateY: 24 },
      upperArmL: { rotate: 42, translateX: 4, translateY: 16 },
      upperArmR: { rotate: -42, translateX: -4, translateY: 16 },
    },
  ],
  ["Tuck pelvis at top", "Drive through heels", "Avoid overextending low back"],
  {
    phase: "concentric",
    repPhases: {
      concentric: { start: 0, end: 0.56, label: "Drive hips up" },
      isometric: { start: 0.56, end: 0.7, label: "Squeeze glutes" },
      eccentric: { start: 0.7, end: 1, label: "Lower under control" },
    },
    style: {
      interpolation: "smoothstep",
      transitionMs: 230,
      shadowPulse: 1.25,
    },
  },
);
