import { createAnimation } from "./shared";

export const jumpingJackAnimation = createAnimation(
  "Jumping Jack",
  1050,
  [
    {
      t: 0,
      upperArmL: { rotate: 8, translateX: 0, translateY: 0 },
      upperArmR: { rotate: -8, translateX: 0, translateY: 0 },
      thighL: { rotate: 0, translateX: -1, translateY: 0 },
      thighR: { rotate: 0, translateX: 1, translateY: 0 },
      shinL: { rotate: 0, translateX: -1, translateY: 0 },
      shinR: { rotate: 0, translateX: 1, translateY: 0 },
    },
    {
      t: 0.22,
      upperArmL: { rotate: 88, translateX: 4, translateY: -4 },
      upperArmR: { rotate: -88, translateX: -4, translateY: -4 },
      foreArmL: { rotate: 10, translateX: 2, translateY: -4 },
      foreArmR: { rotate: -10, translateX: -2, translateY: -4 },
      thighL: { rotate: -14, translateX: -2, translateY: 2 },
      thighR: { rotate: 14, translateX: 2, translateY: 2 },
      shinL: { rotate: 14, translateX: -2, translateY: 4 },
      shinR: { rotate: -14, translateX: 2, translateY: 4 },
      torso: { rotate: 0, translateX: 0, translateY: -1 },
    },
    {
      t: 0.48,
      upperArmL: { rotate: 165, translateX: 6, translateY: -8 },
      upperArmR: { rotate: -165, translateX: -6, translateY: -8 },
      foreArmL: { rotate: 16, translateX: 4, translateY: -6 },
      foreArmR: { rotate: -16, translateX: -4, translateY: -6 },
      thighL: { rotate: -26, translateX: -4, translateY: 4 },
      thighR: { rotate: 26, translateX: 4, translateY: 4 },
      shinL: { rotate: 26, translateX: -3, translateY: 6 },
      shinR: { rotate: -26, translateX: 3, translateY: 6 },
      torso: { rotate: 0, translateX: 0, translateY: -2 },
    },
    {
      t: 0.72,
      upperArmL: { rotate: 96, translateX: 4, translateY: -4 },
      upperArmR: { rotate: -96, translateX: -4, translateY: -4 },
      foreArmL: { rotate: 12, translateX: 2, translateY: -4 },
      foreArmR: { rotate: -12, translateX: -2, translateY: -4 },
      thighL: { rotate: -12, translateX: -2, translateY: 2 },
      thighR: { rotate: 12, translateX: 2, translateY: 2 },
      shinL: { rotate: 12, translateX: -2, translateY: 3 },
      shinR: { rotate: -12, translateX: 2, translateY: 3 },
    },
    {
      t: 1,
      upperArmL: { rotate: 8, translateX: 0, translateY: 0 },
      upperArmR: { rotate: -8, translateX: 0, translateY: 0 },
      thighL: { rotate: 0, translateX: -1, translateY: 0 },
      thighR: { rotate: 0, translateX: 1, translateY: 0 },
      shinL: { rotate: 0, translateX: -1, translateY: 0 },
      shinR: { rotate: 0, translateX: 1, translateY: 0 },
    },
  ],
  ["Land softly", "Stay tall through trunk", "Keep rhythm"],
  {
    phase: "concentric",
    repPhases: {
      concentric: { start: 0, end: 0.48, label: "Open jump" },
      eccentric: { start: 0.48, end: 1, label: "Close jump" },
    },
    style: {
      interpolation: "sine",
      transitionMs: 180,
      shadowPulse: 1.4,
    },
  },
);
