import { createAnimation } from "./shared";

export const pullupAnimation = createAnimation(
  "Pull-up",
  2300,
  [
    {
      t: 0,
      torso: { rotate: 4, translateX: 0, translateY: 6 },
      upperArmL: { rotate: 150, translateX: 4, translateY: -6 },
      foreArmL: { rotate: 35, translateX: 6, translateY: -12 },
      upperArmR: { rotate: -150, translateX: -4, translateY: -6 },
      foreArmR: { rotate: -35, translateX: -6, translateY: -12 },
      thighL: { rotate: 6, translateX: -1, translateY: 4 },
      thighR: { rotate: -6, translateX: 1, translateY: 4 },
    },
    {
      t: 0.3,
      torso: { rotate: 0, translateX: 0, translateY: -2 },
      upperArmL: { rotate: 138, translateX: 3, translateY: -10 },
      foreArmL: { rotate: 52, translateX: 5, translateY: -10 },
      upperArmR: { rotate: -138, translateX: -3, translateY: -10 },
      foreArmR: { rotate: -52, translateX: -5, translateY: -10 },
      thighL: { rotate: 8, translateX: -1, translateY: 3 },
      thighR: { rotate: -8, translateX: 1, translateY: 3 },
    },
    {
      t: 0.54,
      torso: { rotate: -6, translateX: 0, translateY: -12 },
      head: { rotate: 0, translateX: 0, translateY: -10 },
      upperArmL: { rotate: 128, translateX: 3, translateY: -12 },
      foreArmL: { rotate: 64, translateX: 5, translateY: -10 },
      upperArmR: { rotate: -128, translateX: -3, translateY: -12 },
      foreArmR: { rotate: -64, translateX: -5, translateY: -10 },
      thighL: { rotate: 10, translateX: -1, translateY: 2 },
      thighR: { rotate: -10, translateX: 1, translateY: 2 },
    },
    {
      t: 0.66,
      torso: { rotate: -6, translateX: 0, translateY: -12 },
      head: { rotate: 0, translateX: 0, translateY: -10 },
      upperArmL: { rotate: 128, translateX: 3, translateY: -12 },
      foreArmL: { rotate: 64, translateX: 5, translateY: -10 },
      upperArmR: { rotate: -128, translateX: -3, translateY: -12 },
      foreArmR: { rotate: -64, translateX: -5, translateY: -10 },
      thighL: { rotate: 10, translateX: -1, translateY: 2 },
      thighR: { rotate: -10, translateX: 1, translateY: 2 },
    },
    {
      t: 0.88,
      torso: { rotate: 2, translateX: 0, translateY: 1 },
      upperArmL: { rotate: 146, translateX: 4, translateY: -8 },
      foreArmL: { rotate: 40, translateX: 6, translateY: -10 },
      upperArmR: { rotate: -146, translateX: -4, translateY: -8 },
      foreArmR: { rotate: -40, translateX: -6, translateY: -10 },
      thighL: { rotate: 7, translateX: -1, translateY: 3 },
      thighR: { rotate: -7, translateX: 1, translateY: 3 },
    },
    {
      t: 1,
      torso: { rotate: 4, translateX: 0, translateY: 6 },
      upperArmL: { rotate: 150, translateX: 4, translateY: -6 },
      foreArmL: { rotate: 35, translateX: 6, translateY: -12 },
      upperArmR: { rotate: -150, translateX: -4, translateY: -6 },
      foreArmR: { rotate: -35, translateX: -6, translateY: -12 },
      thighL: { rotate: 6, translateX: -1, translateY: 4 },
      thighR: { rotate: -6, translateX: 1, translateY: 4 },
    },
  ],
  ["Start from dead hang", "Drive elbows down", "Keep chest proud"],
  {
    phase: "concentric",
    repPhases: {
      concentric: { start: 0, end: 0.54, label: "Pull to bar" },
      isometric: { start: 0.54, end: 0.66, label: "Hold peak" },
      eccentric: { start: 0.66, end: 1, label: "Lower with control" },
    },
    style: {
      interpolation: "smoothstep",
      transitionMs: 240,
      shadowPulse: 1.05,
    },
  },
);
