import { createAnimation } from "./shared";

export const pushupAnimation = createAnimation(
  "Push-up",
  2200,
  [
    {
      t: 0,
      torso: { rotate: 55, translateX: -2, translateY: 36 },
      upperArmL: { rotate: 72, translateX: 8, translateY: 30 },
      foreArmL: { rotate: 18, translateX: 10, translateY: 36 },
      upperArmR: { rotate: -72, translateX: -8, translateY: 30 },
      foreArmR: { rotate: -18, translateX: -10, translateY: 36 },
      thighL: { rotate: -10, translateX: -3, translateY: 14 },
      thighR: { rotate: -10, translateX: 3, translateY: 14 },
    },
    {
      t: 0.3,
      torso: { rotate: 58, translateX: -2, translateY: 39 },
      upperArmL: { rotate: 82, translateX: 9, translateY: 33 },
      foreArmL: { rotate: 26, translateX: 10, translateY: 37 },
      upperArmR: { rotate: -82, translateX: -9, translateY: 33 },
      foreArmR: { rotate: -26, translateX: -10, translateY: 37 },
      thighL: { rotate: -12, translateX: -4, translateY: 15 },
      thighR: { rotate: -12, translateX: 4, translateY: 15 },
    },
    {
      t: 0.56,
      torso: { rotate: 63, translateX: -2, translateY: 42 },
      upperArmL: { rotate: 92, translateX: 10, translateY: 36 },
      foreArmL: { rotate: 36, translateX: 11, translateY: 39 },
      upperArmR: { rotate: -92, translateX: -10, translateY: 36 },
      foreArmR: { rotate: -36, translateX: -11, translateY: 39 },
      thighL: { rotate: -15, translateX: -4, translateY: 17 },
      thighR: { rotate: -15, translateX: 4, translateY: 17 },
    },
    {
      t: 0.68,
      torso: { rotate: 63, translateX: -2, translateY: 42 },
      upperArmL: { rotate: 92, translateX: 10, translateY: 36 },
      foreArmL: { rotate: 36, translateX: 11, translateY: 39 },
      upperArmR: { rotate: -92, translateX: -10, translateY: 36 },
      foreArmR: { rotate: -36, translateX: -11, translateY: 39 },
      thighL: { rotate: -15, translateX: -4, translateY: 17 },
      thighR: { rotate: -15, translateX: 4, translateY: 17 },
    },
    {
      t: 0.9,
      torso: { rotate: 56, translateX: -2, translateY: 37 },
      upperArmL: { rotate: 74, translateX: 8, translateY: 31 },
      foreArmL: { rotate: 20, translateX: 10, translateY: 35 },
      upperArmR: { rotate: -74, translateX: -8, translateY: 31 },
      foreArmR: { rotate: -20, translateX: -10, translateY: 35 },
      thighL: { rotate: -11, translateX: -3, translateY: 14 },
      thighR: { rotate: -11, translateX: 3, translateY: 14 },
    },
    {
      t: 1,
      torso: { rotate: 55, translateX: -2, translateY: 36 },
      upperArmL: { rotate: 72, translateX: 8, translateY: 30 },
      foreArmL: { rotate: 18, translateX: 10, translateY: 36 },
      upperArmR: { rotate: -72, translateX: -8, translateY: 30 },
      foreArmR: { rotate: -18, translateX: -10, translateY: 36 },
      thighL: { rotate: -10, translateX: -3, translateY: 14 },
      thighR: { rotate: -10, translateX: 3, translateY: 14 },
    },
  ],
  ["Body in one line", "Elbows 45 degrees", "Press away from floor"],
  {
    phase: "concentric",
    repPhases: {
      eccentric: { start: 0, end: 0.56, label: "Lower under control" },
      isometric: { start: 0.56, end: 0.68, label: "Pause near chest" },
      concentric: { start: 0.68, end: 1, label: "Press to lockout" },
    },
    style: {
      interpolation: "smoothstep",
      transitionMs: 220,
      shadowPulse: 1.15,
    },
  },
);
