import { createAnimation } from "./shared";

export const squatAnimation = createAnimation(
  "Barbell Back Squat",
  2550,
  [
    {
      t: 0,
      torso: { rotate: 0, translateX: 0, translateY: 0 },
      thighL: { rotate: 0, translateX: 0, translateY: 0 },
      shinL: { rotate: 0, translateX: 0, translateY: 0 },
      thighR: { rotate: 0, translateX: 0, translateY: 0 },
      shinR: { rotate: 0, translateX: 0, translateY: 0 },
      upperArmL: { rotate: 5, translateX: 0, translateY: 0 },
      upperArmR: { rotate: -5, translateX: 0, translateY: 0 },
    },
    {
      t: 0.28,
      torso: { rotate: 11, translateX: 0, translateY: 20 },
      thighL: { rotate: -62, translateX: -1, translateY: 14 },
      shinL: { rotate: 55, translateX: -1, translateY: 18 },
      thighR: { rotate: -62, translateX: 1, translateY: 14 },
      shinR: { rotate: 55, translateX: 1, translateY: 18 },
      upperArmL: { rotate: 9, translateX: 0, translateY: 6 },
      upperArmR: { rotate: -9, translateX: 0, translateY: 6 },
    },
    {
      t: 0.48,
      torso: { rotate: 17, translateX: 0, translateY: 34 },
      thighL: { rotate: -98, translateX: -2, translateY: 26 },
      shinL: { rotate: 92, translateX: -1, translateY: 30 },
      thighR: { rotate: -98, translateX: 2, translateY: 26 },
      shinR: { rotate: 92, translateX: 1, translateY: 30 },
      upperArmL: { rotate: 12, translateX: 0, translateY: 10 },
      upperArmR: { rotate: -12, translateX: 0, translateY: 10 },
    },
    {
      t: 0.58,
      torso: { rotate: 20, translateX: 0, translateY: 40 },
      thighL: { rotate: -110, translateX: -3, translateY: 30 },
      shinL: { rotate: 105, translateX: -1, translateY: 34 },
      thighR: { rotate: -110, translateX: 3, translateY: 30 },
      shinR: { rotate: 105, translateX: 1, translateY: 34 },
      upperArmL: { rotate: 14, translateX: 0, translateY: 12 },
      upperArmR: { rotate: -14, translateX: 0, translateY: 12 },
    },
    {
      t: 0.78,
      torso: { rotate: 8, translateX: 0, translateY: 12 },
      thighL: { rotate: -28, translateX: -1, translateY: 10 },
      shinL: { rotate: 26, translateX: 0, translateY: 11 },
      thighR: { rotate: -28, translateX: 1, translateY: 10 },
      shinR: { rotate: 26, translateX: 0, translateY: 11 },
    },
    {
      t: 0.92,
      torso: { rotate: -2, translateX: 0, translateY: -2 },
      thighL: { rotate: 8, translateX: 0, translateY: -1 },
      shinL: { rotate: -6, translateX: 0, translateY: -1 },
      thighR: { rotate: 8, translateX: 0, translateY: -1 },
      shinR: { rotate: -6, translateX: 0, translateY: -1 },
      head: { rotate: 0, translateX: 0, translateY: -1 },
    },
    {
      t: 1,
      torso: { rotate: 0, translateX: 0, translateY: 0 },
      thighL: { rotate: 0, translateX: 0, translateY: 0 },
      shinL: { rotate: 0, translateX: 0, translateY: 0 },
      thighR: { rotate: 0, translateX: 0, translateY: 0 },
      shinR: { rotate: 0, translateX: 0, translateY: 0 },
      upperArmL: { rotate: 5, translateX: 0, translateY: 0 },
      upperArmR: { rotate: -5, translateX: 0, translateY: 0 },
    },
  ],
  [
    "Chest up, back straight",
    "Drive knees out over toes",
    "Break at hips first then knees",
    "Drive through heels on ascent",
  ],
  {
    phase: "concentric",
    repPhases: {
      eccentric: { start: 0, end: 0.58, label: "Lower with control" },
      isometric: { start: 0.58, end: 0.64, label: "Own the bottom" },
      concentric: { start: 0.64, end: 1, label: "Drive up" },
    },
    style: {
      interpolation: "smoothstep",
      transitionMs: 240,
      shadowPulse: 1.3,
    },
  },
);
