begin;

insert into public.country_cuisines (
  country_code,
  country_name,
  cuisine_tags,
  staples,
  proteins,
  carbs,
  vegetables
)
values
  ('ZW', 'Zimbabwe', array['sadza','nyama','muriwo','matemba','nhopi','maputi','mahewu','amasi'], array['sadza','mutakura','muriwo','maputi'], array['beef','chicken','goat','tilapia','matemba'], array['sadza','sweet_potato','cassava','rice'], array['morogo','tomato','onion','covo']),
  ('ZA', 'South Africa', array['pap','braai','boerewors','bobotie','vetkoek','samp'], array['pap','samp','vetkoek','rice'], array['beef','lamb','chicken','snoek','boerewors'], array['pap','rice','bread','potato'], array['spinach','butternut','peas','carrots']),
  ('ZM', 'Zambia', array['nshima','ifisashi','kapenta','chikanda','vitumbuwa'], array['nshima','cassava','sweet_potato'], array['beef','chicken','kapenta','beans'], array['nshima','cassava','rice','sweet_potato'], array['rape','pumpkin_leaves','tomato','onion']),
  ('BW', 'Botswana', array['bogobe','seswaa','morogo','dikgobe','vetkoek'], array['bogobe','sorghum','beans'], array['beef','goat','chicken','beans'], array['sorghum','maize','rice','sweet_potato'], array['morogo','pumpkin','cabbage','tomato']),
  ('NA', 'Namibia', array['mahangu','kapana','oshifima','vetkoek','bream'], array['mahangu','oshifima','vetkoek'], array['beef','goat','fish','game'], array['mahangu','maize','rice','potato'], array['spinach','pumpkin','tomato','onion']),
  ('MZ', 'Mozambique', array['xima','matapa','piri_piri','cassava','peri_peri_chicken'], array['xima','cassava','rice'], array['prawns','chicken','fish','beans'], array['xima','cassava','rice','sweet_potato'], array['cassava_leaves','tomato','onion','cabbage']),
  ('MW', 'Malawi', array['nsima','chambo','ndiwo','thela','kondowole'], array['nsima','cassava','sweet_potato'], array['chambo','goat','beans','chicken'], array['nsima','cassava','rice','sweet_potato'], array['mustard_greens','pumpkin_leaves','tomato','onion']),
  ('KE', 'Kenya', array['ugali','nyama_choma','sukuma_wiki','githeri','irio','chapati'], array['ugali','githeri','chapati','sweet_potato'], array['beef','goat','tilapia','chicken','beans'], array['ugali','rice','chapati','sweet_potato'], array['sukuma_wiki','spinach','cabbage','tomato']),
  ('UG', 'Uganda', array['matoke','posho','groundnut_stew','luwombo','chapati'], array['matoke','posho','cassava','rice'], array['beef','goat','tilapia','beans','groundnuts'], array['matoke','posho','cassava','rice'], array['nakati','spinach','tomato','onion']),
  ('TZ', 'Tanzania', array['ugali','wali','nyama_choma','mshikaki','ndizi'], array['ugali','rice','plantain','cassava'], array['beef','goat','fish','chicken'], array['ugali','rice','plantain','cassava'], array['mchicha','cabbage','tomato','onion']),
  ('RW', 'Rwanda', array['ugali','isombe','brochettes','ibirayi','beans'], array['ugali','cassava','potato','beans'], array['goat','beef','beans','fish'], array['ugali','cassava','potato','rice'], array['cassava_leaves','cabbage','tomato','onion']),
  ('ET', 'Ethiopia', array['injera','tibs','shiro','kitfo','doro_wat','teff_porridge'], array['injera','teff','rice'], array['beef','lamb','chicken','lentils','chickpeas'], array['injera','teff','rice'], array['gomen','tomato','onion','cabbage']),
  ('ER', 'Eritrea', array['injera','zigni','shiro','hilbet','alicha'], array['injera','teff','sorghum'], array['beef','lamb','lentils','chickpeas'], array['injera','teff','rice'], array['greens','tomato','onion','cabbage']),
  ('NG', 'Nigeria', array['jollof_rice','egusi','suya','pounded_yam','moi_moi','akara'], array['yam','rice','cassava','plantain'], array['beef','goat','tilapia','catfish','chicken'], array['yam','rice','plantain','cassava'], array['ugu','spinach','tomato','pepper']),
  ('GH', 'Ghana', array['fufu','jollof_rice','kelewele','waakye','kenkey','light_soup'], array['fufu','rice','yam','plantain'], array['tilapia','catfish','chicken','beef','tuna'], array['fufu','rice','yam','plantain'], array['garden_egg','tomato','pepper','spinach']),
  ('CI', 'Cote d''Ivoire', array['attieke','alloco','kedjenou','garba','peanut_stew'], array['cassava','rice','plantain'], array['fish','chicken','beef','goat'], array['cassava','rice','plantain','yam'], array['eggplant','tomato','pepper','okra']),
  ('SN', 'Senegal', array['thieboudienne','yassa','maafe','fonio','pastels'], array['rice','fonio','millet'], array['fish','chicken','beef','lamb'], array['rice','fonio','millet','sweet_potato'], array['carrot','cabbage','tomato','onion']),
  ('CM', 'Cameroon', array['ndole','eru','achu','koki','jollof_rice'], array['cassava','plantain','cornmeal'], array['beef','fish','chicken','beans'], array['cassava','plantain','rice','cornmeal'], array['eru','ndole','tomato','onion']),
  ('EG', 'Egypt', array['ful_medames','koshari','molokhia','shawarma','baladi_bread'], array['rice','baladi_bread','lentils'], array['beef','chicken','fish','lentils'], array['rice','bread','lentils','potato'], array['molokhia','tomato','cucumber','onion']),
  ('MA', 'Morocco', array['couscous','tagine','harira','bissara','zaalouk'], array['couscous','bread','lentils'], array['lamb','chicken','sardines','chickpeas'], array['couscous','bread','potato','rice'], array['carrot','zucchini','tomato','eggplant']),
  ('IN', 'India', array['dal','rice','roti','curry','sabzi','biryani','idli','dosa'], array['rice','roti','potato'], array['chicken','mutton','fish','lentils','paneer','eggs'], array['rice','roti','bread','potato'], array['spinach','cauliflower','potato','tomato','onion']),
  ('PK', 'Pakistan', array['biryani','dal','roti','nihari','haleem'], array['rice','roti','lentils'], array['chicken','beef','mutton','lentils'], array['rice','roti','bread','potato'], array['spinach','okra','tomato','onion']),
  ('BD', 'Bangladesh', array['bhat','dal','bhuna','khichuri','hilsa'], array['rice','flatbread','lentils'], array['fish','chicken','beef','lentils'], array['rice','flatbread','potato','lentils'], array['spinach','pumpkin','eggplant','tomato']),
  ('LK', 'Sri Lanka', array['rice_and_curry','hoppers','kottu','dhal','pol_sambol'], array['rice','hoppers','roti'], array['fish','chicken','lentils','eggs'], array['rice','roti','hoppers','cassava'], array['gotukola','jackfruit','tomato','onion']),
  ('CN', 'China', array['rice','congee','noodles','stir_fry','dumplings'], array['rice','noodles','bao'], array['pork','chicken','beef','tofu','fish'], array['rice','noodles','bao','sweet_potato'], array['bok_choy','cabbage','broccoli','mushrooms']),
  ('JP', 'Japan', array['rice','miso_soup','yakitori','soba','onigiri'], array['rice','soba','udon'], array['salmon','tuna','chicken','tofu','eggs'], array['rice','soba','udon','sweet_potato'], array['seaweed','cabbage','daikon','edamame']),
  ('KR', 'South Korea', array['bibimbap','kimchi','bulgogi','doenjang','gimbap'], array['rice','sweet_potato','noodles'], array['beef','chicken','tofu','eggs','fish'], array['rice','noodles','sweet_potato','barley'], array['kimchi','spinach','bean_sprouts','cucumber']),
  ('TH', 'Thailand', array['jasmine_rice','tom_yum','green_curry','pad_krapow','som_tam'], array['rice','rice_noodles','sticky_rice'], array['chicken','prawns','fish','tofu','eggs'], array['rice','rice_noodles','sticky_rice','cassava'], array['morning_glory','green_papaya','cabbage','basil']),
  ('VN', 'Vietnam', array['pho','bun','com_tam','banh_mi','goi_cuon'], array['rice','rice_noodles','banh_mi'], array['beef','chicken','pork','tofu','fish'], array['rice','rice_noodles','banh_mi','sweet_potato'], array['herbs','bean_sprouts','cucumber','carrot']),
  ('PH', 'Philippines', array['adobo','tinola','lugaw','sinigang','tapsilog'], array['rice','noodles','sweet_potato'], array['chicken','pork','beef','fish','eggs'], array['rice','noodles','sweet_potato','bread'], array['kangkong','eggplant','tomato','okra']),
  ('ID', 'Indonesia', array['nasi_goreng','gado_gado','soto','tempeh','satay'], array['rice','noodles','cassava'], array['chicken','beef','fish','tempeh','tofu'], array['rice','noodles','cassava','sweet_potato'], array['water_spinach','cabbage','bean_sprouts','cucumber']),
  ('MY', 'Malaysia', array['nasi_lemak','laksa','roti_canai','satay','rendang'], array['rice','noodles','roti'], array['chicken','beef','fish','eggs','tofu'], array['rice','noodles','roti','cassava'], array['kangkung','cabbage','bean_sprouts','cucumber']),
  ('AE', 'United Arab Emirates', array['machboos','harees','grilled_meat','hummus','khubz'], array['rice','khubz','harees'], array['lamb','chicken','fish','chickpeas'], array['rice','khubz','wheat'], array['cucumber','tomato','parsley','lettuce']),
  ('SA', 'Saudi Arabia', array['kabsa','harees','shawarma','labneh','khubz'], array['rice','khubz','wheat'], array['lamb','chicken','beef','fish'], array['rice','khubz','wheat','potato'], array['cucumber','tomato','parsley','lettuce']),
  ('TR', 'Turkey', array['pilaf','kebab','menemen','mercimek','yogurt'], array['rice','bulgur','bread'], array['lamb','beef','chicken','lentils','yogurt'], array['rice','bulgur','bread','potato'], array['tomato','cucumber','eggplant','pepper']),
  ('GR', 'Greece', array['greek_yogurt','souvlaki','fasolada','spanakopita','horiatiki'], array['bread','rice','potato'], array['fish','chicken','lamb','yogurt','beans'], array['bread','rice','potato','barley'], array['tomato','cucumber','spinach','olive']),
  ('IT', 'Italy', array['risotto','pasta','minestrone','polenta','frittata'], array['pasta','polenta','bread'], array['chicken','beef','fish','beans','cheese'], array['pasta','polenta','bread','rice'], array['tomato','zucchini','eggplant','spinach']),
  ('ES', 'Spain', array['paella','tortilla','gazpacho','fabada','pan_con_tomate'], array['rice','bread','potato'], array['fish','chicken','pork','beans','eggs'], array['rice','bread','potato','beans'], array['tomato','pepper','onion','spinach']),
  ('FR', 'France', array['ratatouille','omelette','salade_nicoise','potage','yogurt'], array['bread','potato','rice'], array['chicken','beef','fish','eggs','yogurt'], array['bread','potato','rice','beans'], array['zucchini','tomato','eggplant','green_beans']),
  ('GB', 'United Kingdom', array['porridge','jacket_potato','fish_and_peas','beans_on_toast','stew'], array['oats','potato','bread'], array['beef','chicken','fish','eggs','beans'], array['oats','potato','bread','rice'], array['peas','broccoli','carrot','spinach']),
  ('US', 'United States', array['oats','chili','grilled_chicken','sweet_potato','yogurt_bowl'], array['oats','potato','rice','bread'], array['chicken','beef','turkey','salmon','eggs','greek_yogurt'], array['oats','rice','potato','bread'], array['broccoli','spinach','kale','tomato']),
  ('CA', 'Canada', array['oatmeal','salmon','chili','lentil_soup','roasted_potato'], array['oats','potato','rice','bread'], array['salmon','chicken','beef','turkey','lentils'], array['oats','potato','rice','bread'], array['kale','broccoli','carrot','spinach']),
  ('MX', 'Mexico', array['tortillas','beans','rice','carne_asada','pozole','salsa'], array['corn_tortilla','rice','beans'], array['beef','chicken','beans','eggs','fish'], array['corn_tortilla','rice','beans','sweet_potato'], array['tomato','pepper','onion','avocado']),
  ('BR', 'Brazil', array['feijoada','rice','farofa','pao_de_queijo','acai'], array['rice','cassava','beans'], array['beef','chicken','fish','beans','eggs'], array['rice','cassava','beans','sweet_potato'], array['collard_greens','tomato','onion','pepper']),
  ('AR', 'Argentina', array['asado','milanesa','empanada','polenta','chimichurri'], array['bread','polenta','potato'], array['beef','chicken','fish','eggs'], array['bread','polenta','potato','rice'], array['tomato','lettuce','pumpkin','onion']),
  ('AU', 'Australia', array['oats','grilled_fish','pumpkin','avocado_toast','yogurt'], array['oats','bread','potato','rice'], array['beef','chicken','fish','eggs','yogurt'], array['oats','bread','potato','rice'], array['pumpkin','spinach','tomato','broccoli']),
  ('NZ', 'New Zealand', array['porridge','kumara','lamb','salmon','yogurt'], array['oats','kumara','bread'], array['lamb','fish','beef','eggs','yogurt'], array['oats','kumara','bread','rice'], array['spinach','broccoli','pumpkin','tomato'])
on conflict (country_code) do update
set country_name = excluded.country_name,
    cuisine_tags = excluded.cuisine_tags,
    staples = excluded.staples,
    proteins = excluded.proteins,
    carbs = excluded.carbs,
    vegetables = excluded.vegetables,
    updated_at = now();

insert into public.regional_foods (
  name,
  local_name,
  country_codes,
  calories_per_100g,
  protein_g,
  carbs_g,
  fat_g,
  fiber_g,
  iron_mg,
  calcium_mg,
  sodium_mg,
  category
)
select seed.name,
       seed.local_name,
       seed.country_codes,
       seed.calories_per_100g,
       seed.protein_g,
       seed.carbs_g,
       seed.fat_g,
       seed.fiber_g,
       seed.iron_mg,
       seed.calcium_mg,
       seed.sodium_mg,
       seed.category
from (
  values
    ('Pap (Cooked)', null, array['ZA','BW']::text[], 94.0, 2.1, 20.8, 0.4, 1.4, null, 2.0, 2.0, 'grain'),
    ('Nshima (Cooked)', null, array['ZM']::text[], 96.0, 2.2, 21.3, 0.4, 1.6, null, null, 2.0, 'grain'),
    ('Nsima (Cooked)', null, array['MW']::text[], 95.0, 2.1, 21.1, 0.4, 1.6, null, null, 2.0, 'grain'),
    ('Teff Porridge', null, array['ET','ER']::text[], 122.0, 4.1, 23.0, 1.1, 3.7, 2.8, 18.0, 40.0, 'grain'),
    ('Muriwo Unedovi', null, array['ZW']::text[], 112.0, 4.3, 8.1, 7.4, 3.2, 2.8, 88.0, 170.0, 'mixed_dish'),
    ('Waakye', null, array['GH']::text[], 167.0, 6.2, 29.4, 2.1, 4.3, 1.9, 28.0, 140.0, 'mixed_dish'),
    ('Kenkey', null, array['GH']::text[], 163.0, 3.1, 35.4, 0.9, 2.6, null, null, 190.0, 'grain'),
    ('Fufu', null, array['GH','NG','CI']::text[], 154.0, 1.3, 36.0, 0.2, 1.8, null, null, 6.0, 'grain'),
    ('Pounded Yam', null, array['NG']::text[], 118.0, 1.5, 27.8, 0.2, 2.3, null, null, 8.0, 'grain'),
    ('Egusi Soup', null, array['NG']::text[], 221.0, 8.4, 7.8, 18.0, 2.8, 2.3, 62.0, 320.0, 'mixed_dish'),
    ('Moi Moi', null, array['NG']::text[], 169.0, 11.2, 14.3, 7.1, 4.6, 2.8, 36.0, 170.0, 'legume'),
    ('Akara', null, array['NG']::text[], 215.0, 10.7, 17.5, 11.9, 5.1, 2.4, 41.0, 210.0, 'legume'),
    ('Attieke', null, array['CI']::text[], 166.0, 1.5, 39.1, 0.2, 1.8, null, null, 14.0, 'grain'),
    ('Thieboudienne', null, array['SN']::text[], 171.0, 8.7, 24.8, 4.3, 2.4, 1.1, 26.0, 240.0, 'mixed_dish'),
    ('Maafe', null, array['SN']::text[], 187.0, 9.0, 8.6, 13.4, 2.6, 1.8, 39.0, 270.0, 'mixed_dish'),
    ('Ndole', null, array['CM']::text[], 148.0, 10.1, 7.4, 9.2, 4.4, 3.6, 112.0, 220.0, 'mixed_dish'),
    ('Koki Beans', null, array['CM']::text[], 173.0, 9.5, 21.7, 5.1, 6.2, 2.2, 46.0, 120.0, 'legume'),
    ('Irio', null, array['KE']::text[], 126.0, 4.2, 23.5, 1.1, 4.2, 1.2, 24.0, 85.0, 'mixed_dish'),
    ('Kachumbari', null, array['KE','TZ','UG']::text[], 32.0, 1.0, 6.8, 0.2, 1.7, 0.7, 18.0, 36.0, 'vegetable'),
    ('Matoke', null, array['UG']::text[], 120.0, 1.3, 31.9, 0.4, 2.3, null, null, 3.0, 'grain'),
    ('Luwombo Chicken', null, array['UG']::text[], 173.0, 19.2, 4.3, 8.1, 1.4, 1.2, 21.0, 180.0, 'mixed_dish'),
    ('Isombe', null, array['RW']::text[], 118.0, 3.8, 8.4, 8.1, 3.6, 2.5, 81.0, 150.0, 'mixed_dish'),
    ('Chambo (Grilled)', null, array['MW']::text[], 148.0, 26.2, 0.0, 4.5, 0.0, null, 24.0, 78.0, 'protein'),
    ('Matapa', null, array['MZ']::text[], 161.0, 5.2, 8.2, 11.3, 4.8, 2.7, 96.0, 180.0, 'mixed_dish'),
    ('Piri Piri Chicken', null, array['MZ']::text[], 208.0, 24.8, 3.8, 10.4, 0.4, null, null, 330.0, 'protein'),
    ('Bogobe', null, array['BW']::text[], 109.0, 3.1, 22.5, 0.8, 2.8, 1.2, 7.0, 12.0, 'grain'),
    ('Seswaa', null, array['BW']::text[], 226.0, 28.4, 0.0, 12.4, 0.0, 2.9, 18.0, 110.0, 'protein'),
    ('Mahangu Porridge', null, array['NA']::text[], 104.0, 3.4, 21.1, 1.2, 2.9, 2.0, 8.0, 9.0, 'grain'),
    ('Kapana Beef', null, array['NA']::text[], 239.0, 28.7, 1.8, 13.1, 0.1, 3.1, 20.0, 290.0, 'protein'),
    ('Ful Medames', null, array['EG']::text[], 135.0, 7.8, 18.6, 3.1, 5.4, 2.0, 34.0, 190.0, 'legume'),
    ('Koshari', null, array['EG']::text[], 168.0, 5.7, 30.2, 2.2, 4.6, 1.7, 24.0, 260.0, 'mixed_dish'),
    ('Molokhia', null, array['EG']::text[], 43.0, 3.4, 6.1, 0.4, 2.8, 1.5, 140.0, 38.0, 'vegetable'),
    ('Couscous', null, array['MA']::text[], 112.0, 3.8, 23.2, 0.2, 1.4, 0.4, 8.0, 5.0, 'grain'),
    ('Harira', null, array['MA']::text[], 96.0, 4.9, 12.8, 2.8, 2.7, 1.4, 21.0, 210.0, 'mixed_dish'),
    ('Roti', null, array['IN','PK','BD','LK']::text[], 297.0, 9.6, 46.4, 7.5, 6.3, 3.5, 35.0, 280.0, 'grain'),
    ('Chicken Biryani', null, array['IN','PK']::text[], 183.0, 9.7, 23.4, 5.9, 1.3, 1.2, 19.0, 320.0, 'mixed_dish'),
    ('Idli', null, array['IN']::text[], 146.0, 4.5, 28.6, 1.2, 1.5, null, null, 130.0, 'grain'),
    ('Dosa', null, array['IN']::text[], 184.0, 4.4, 30.7, 4.2, 1.9, null, null, 220.0, 'grain'),
    ('Congee', null, array['CN']::text[], 49.0, 1.1, 10.4, 0.2, 0.2, null, null, 48.0, 'grain'),
    ('Tofu Stir Fry', null, array['CN']::text[], 112.0, 7.1, 7.9, 5.8, 2.2, 1.3, 98.0, 240.0, 'mixed_dish'),
    ('Miso Soup', null, array['JP']::text[], 35.0, 2.4, 4.5, 1.1, 0.8, null, 18.0, 630.0, 'beverage'),
    ('Kimchi', null, array['KR']::text[], 17.0, 1.1, 3.6, 0.5, 1.6, 0.4, 33.0, 498.0, 'vegetable'),
    ('Pho', null, array['VN']::text[], 72.0, 5.3, 8.1, 2.1, 0.7, null, null, 330.0, 'mixed_dish'),
    ('Chicken Adobo', null, array['PH']::text[], 190.0, 19.7, 3.5, 10.4, 0.2, null, null, 520.0, 'mixed_dish'),
    ('Tempeh', null, array['ID']::text[], 193.0, 20.3, 7.6, 10.8, 1.4, 2.7, 111.0, 9.0, 'protein'),
    ('Nasi Lemak', null, array['MY']::text[], 205.0, 4.7, 23.6, 10.1, 1.4, null, null, 240.0, 'mixed_dish'),
    ('Kabsa', null, array['SA']::text[], 186.0, 11.1, 25.1, 4.3, 1.2, null, null, 260.0, 'mixed_dish'),
    ('Hummus', null, array['AE','SA','TR','GR']::text[], 166.0, 7.9, 14.3, 9.6, 6.0, 2.4, 49.0, 240.0, 'legume'),
    ('Fasolada', null, array['GR']::text[], 102.0, 5.4, 15.8, 2.0, 4.8, 1.8, 47.0, 190.0, 'legume'),
    ('Polenta', null, array['IT','AR']::text[], 85.0, 1.9, 18.4, 0.6, 1.5, 0.4, 2.0, 3.0, 'grain'),
    ('Minestrone', null, array['IT']::text[], 63.0, 2.9, 10.2, 1.2, 2.3, null, null, 210.0, 'mixed_dish'),
    ('Paella', null, array['ES']::text[], 158.0, 8.9, 18.3, 5.5, 1.3, null, null, 260.0, 'mixed_dish'),
    ('Ratatouille', null, array['FR']::text[], 72.0, 1.5, 6.7, 4.4, 2.6, 0.5, 20.0, 160.0, 'vegetable'),
    ('Baked Beans', null, array['GB']::text[], 94.0, 4.8, 16.4, 0.4, 3.7, 1.2, 43.0, 422.0, 'legume'),
    ('Turkey Chili', null, array['US','CA']::text[], 134.0, 12.4, 10.7, 5.1, 3.8, 1.5, 36.0, 320.0, 'mixed_dish'),
    ('Black Beans (Cooked)', null, array['MX','US','BR']::text[], 132.0, 8.9, 23.7, 0.5, 8.7, 2.1, 27.0, 1.0, 'legume'),
    ('Corn Tortilla', null, array['MX']::text[], 218.0, 5.7, 44.6, 2.9, 6.3, 1.5, 81.0, 45.0, 'grain'),
    ('Carne Asada', null, array['MX']::text[], 247.0, 25.9, 1.7, 15.3, 0.1, 2.7, 18.0, 280.0, 'protein'),
    ('Feijoada', null, array['BR']::text[], 176.0, 10.2, 14.1, 8.7, 4.4, 2.1, 35.0, 350.0, 'mixed_dish'),
    ('Farofa', null, array['BR']::text[], 380.0, 2.7, 79.1, 5.1, 6.4, null, null, 12.0, 'grain'),
    ('Chimichurri Beef', null, array['AR']::text[], 228.0, 27.4, 1.3, 12.3, 0.2, 2.8, 19.0, 240.0, 'protein'),
    ('Quinoa (Cooked)', null, array['US','CA']::text[], 120.0, 4.4, 21.3, 1.9, 2.8, 1.5, 17.0, 7.0, 'grain'),
    ('Kumara (Boiled)', null, array['NZ']::text[], 82.0, 1.6, 19.1, 0.1, 2.8, 0.7, 30.0, 42.0, 'grain')
) as seed(
  name,
  local_name,
  country_codes,
  calories_per_100g,
  protein_g,
  carbs_g,
  fat_g,
  fiber_g,
  iron_mg,
  calcium_mg,
  sodium_mg,
  category
)
where not exists (
  select 1
  from public.regional_foods rf
  where lower(rf.name) = lower(seed.name)
);

commit;
